[themes.catppuccin.nvim]
colorscheme = "catppuccin"
plugin = "catppuccin/nvim"

[themes.catppuccin.colors]
# Base
bg = "#1e1e2e"
fg = "#cdd6f4"

# Normal colors
black   = "#45475a"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#89b4fa"
magenta = "#f5c2e7"
cyan    = "#94e2d5"
white   = "#bac2de"

# Bright / misc
gray = "#7f849c"
