[themes.gruvbox.colors]
# Base
bg = "#282828"
fg = "#dfbf8e"

# Normal colors
black   = "#665c54"
red     = "#ea6962"
green   = "#a9b665"
yellow  = "#e78a4e"
blue    = "#7daea3"
magenta = "#d3869b"
cyan    = "#89b482"
white   = "#dfbf8e"

# Bright / misc
gray = "#928374"
