[themes.gruvbox.nvim]
colorscheme = "gruvbox-material"
plugin = "sainnhe/gruvbox-material"

[themes.gruvbox.colors]
# Base
bg = "#282828"        # bg0
fg = "#d4be98"        # fg0

# Normal colors
black   = "#5a524c"   # bg5
red     = "#ea6962"
green   = "#a9b665"
yellow  = "#d8a657"
blue    = "#7daea3"
magenta = "#d3869b"
cyan    = "#89b482"
white   = "#ddc7a1"   # fg1

# Bright / misc
gray = "#928374"     # grey1
