[themes.nord.nvim]
colorscheme = "nord"
plugin = "nordtheme/vim"

[themes.nord.colors]
# Base
bg = "#2e3440"
fg = "#d8dee9"

# Normal colors
black   = "#3b4252"
red     = "#bf616a"
green   = "#a3be8c"
yellow  = "#ebcb8b"
blue    = "#81a1c1"
magenta = "#b48ead"
cyan    = "#88c0d0"
white   = "#e5e9f0"

# Bright / misc
gray = "#4c566a"
